const top = [
  {
    rank: 1,
    user: '/user/5',
    fullName: 'Байкалов Илья',
    level: 5,
    exp: 322,
    achieve: [
      { icon: 'mdi-text-box-plus-outline', value: 12 },
      { icon: 'mdi-comment-processing-outline', value: 7 },
      { icon: 'mdi-clock-time-four-outline', value: 14 },
    ],
  },
  {
    rank: 2,
    user: '/user/4',
    fullName: 'Соколовский Никита',
    level: 4,
    exp: 298,
    achieve: [
      { icon: 'mdi-text-box-plus-outline', value: 11 },
      { icon: 'mdi-comment-processing-outline', value: 6 },
      { icon: 'mdi-clock-time-four-outline', value: 10 },
    ],
  },
  {
    rank: 3,
    user: '/user/3',
    fullName: 'Фабричкина Мария',
    level: 3,
    exp: 268,
    achieve: [
      { icon: 'mdi-text-box-plus-outline', value: 9 },
      { icon: 'mdi-comment-processing-outline', value: 7 },
      { icon: 'mdi-clock-time-four-outline', value: 7 },
    ],
  },
  {
    rank: 4,
    user: '/user/6',
    fullName: 'Телков Андрей',
    level: 3,
    exp: 259,
    achieve: [
      { icon: 'mdi-text-box-plus-outline', value: 6 },
      { icon: 'mdi-comment-processing-outline', value: 5 },
      { icon: 'mdi-clock-time-four-outline', value: 7 },
    ],
  },
  {
    rank: 5,
    user: '/user/12',
    fullName: 'Богачев Иван',
    level: 2,
    exp: 183,
    achieve: [
      { icon: 'mdi-text-box-plus-outline', value: 5 },
      { icon: 'mdi-comment-processing-outline', value: 5 },
      { icon: 'mdi-clock-time-four-outline', value: 5 },
    ],
  },
  {
    rank: 6,
    user: '/user/8',
    fullName: 'Сидоров Алексей',
    level: 2,
    exp: 180,
    achieve: [
      { icon: 'mdi-text-box-plus-outline', value: 4 },
      { icon: 'mdi-comment-processing-outline', value: 4 },
      { icon: 'mdi-clock-time-four-outline', value: 5 },
    ],
  },
  {
    rank: 7,
    user: '/user/9',
    fullName: 'Шишкова Ангелина',
    level: 2,
    exp: 174,
    achieve: [
      { icon: 'mdi-text-box-plus-outline', value: 4 },
      { icon: 'mdi-comment-processing-outline', value: 4 },
      { icon: 'mdi-clock-time-four-outline', value: 5 },
    ],
  },
  {
    rank: 8,
    user: '/user/10',
    fullName: 'Карамчак Светлана',
    level: 2,
    exp: 154,
    achieve: [
      { icon: 'mdi-text-box-plus-outline', value: 3 },
      { icon: 'mdi-comment-processing-outline', value: 4 },
      { icon: 'mdi-clock-time-four-outline', value: 5 },
    ],
  },
  {
    rank: 9,
    user: '/user/11',
    fullName: 'Сорока Евгения',
    level: 2,
    exp: 121,
    achieve: [
      { icon: 'mdi-text-box-plus-outline', value: 1 },
      { icon: 'mdi-comment-processing-outline', value: 6 },
      { icon: 'mdi-clock-time-four-outline', value: 4 },
    ],
  },
  {
    rank: 10,
    user: '/user/7',
    fullName: 'Иванов Иван',
    level: 1,
    exp: 95,
    achieve: [
      { icon: 'mdi-text-box-plus-outline', value: 3 },
      { icon: 'mdi-comment-processing-outline', value: 3 },
      { icon: 'mdi-clock-time-four-outline', value: 4 },
    ],
  },
  {
    rank: 11,
    user: '/user/7',
    fullName: 'Петров Петр',
    level: 1,
    exp: 89,
    achieve: [
      { icon: 'mdi-text-box-plus-outline', value: 3 },
      { icon: 'mdi-comment-processing-outline', value: 3 },
      { icon: 'mdi-clock-time-four-outline', value: 3 },
    ],
  },
  {
    rank: 12,
    user: '/user/7',
    fullName: 'Александрова Ксения',
    level: 1,
    exp: 71,
    achieve: [
      { icon: 'mdi-text-box-plus-outline', value: 0 },
      { icon: 'mdi-comment-processing-outline', value: 2 },
      { icon: 'mdi-clock-time-four-outline', value: 3 },
    ],
  },
  {
    rank: 13,
    user: '/user/7',
    fullName: 'Ефремова Татьяна',
    level: 1,
    exp: 50,
    achieve: [
      { icon: 'mdi-text-box-plus-outline', value: 0 },
      { icon: 'mdi-comment-processing-outline', value: 3 },
      { icon: 'mdi-clock-time-four-outline', value: 2 },
    ],
  },
  {
    rank: 14,
    user: '/user/7',
    fullName: 'Никольский Андрей',
    level: 1,
    exp: 34,
    achieve: [
      { icon: 'mdi-text-box-plus-outline', value: 0 },
      { icon: 'mdi-comment-processing-outline', value: 1 },
      { icon: 'mdi-clock-time-four-outline', value: 1 },
    ],
  },
  {
    rank: 15,
    user: '/user/7',
    fullName: 'Елкин Илья',
    level: 1,
    exp: 17,
    achieve: [
      { icon: 'mdi-text-box-plus-outline', value: 0 },
      { icon: 'mdi-comment-processing-outline', value: 1 },
      { icon: 'mdi-clock-time-four-outline', value: 1 },
    ],
  },
];

export default top;
